# Generated by Django 5.1.15 on 2026-03-02 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("human_resources", "0009_add_company_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("leave_approved", "Leave Approved"),
                            ("leave_rejected", "Leave Rejected"),
                            ("leave_request", "New Leave Request"),
                            ("expense_approved", "Expense Approved"),
                            ("expense_rejected", "Expense Rejected"),
                            ("ticket_update", "Ticket Update"),
                            ("ticket_resolved", "Ticket Resolved"),
                            ("payslip_available", "Payslip Available"),
                            ("announcement", "Announcement"),
                            ("system", "System Notification"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "related_object_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("related_object_id", models.IntegerField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_notifications",
                        to="human_resources.employees",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
