# Generated by Django 5.1.15 on 2026-03-03 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_portal", "0003_supportticket_ticketmessage"),
        ("human_resources", "0009_add_company_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon name for display", max_length=50
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Document Category",
                "verbose_name_plural": "Document Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("file", models.FileField(upload_to="portal_documents/%Y/%m/")),
                (
                    "file_type",
                    models.CharField(
                        blank=True,
                        help_text="Auto-detected file type (pdf, doc, xls, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, help_text="File size in bytes"
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("all", "All Employees"),
                            ("department", "Department Only"),
                            ("specific", "Specific Employees"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("is_latest", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "requires_acknowledgement",
                    models.BooleanField(
                        default=False,
                        help_text="Employees must acknowledge reading this document",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("download_count", models.PositiveIntegerField(default=0)),
                (
                    "allowed_employees",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific employees who can access this document (when visibility is 'specific')",
                        related_name="specific_documents",
                        to="human_resources.employees",
                    ),
                ),
                (
                    "departments",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Departments that can access this document (when visibility is 'department')",
                        related_name="accessible_documents",
                        to="human_resources.department",
                    ),
                ),
                (
                    "parent_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versions",
                        to="employee_portal.document",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to="human_resources.employees",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="employee_portal.documentcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentAcknowledgement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acknowledged_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acknowledgements",
                        to="employee_portal.document",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_acknowledgements",
                        to="human_resources.employees",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Acknowledgement",
                "verbose_name_plural": "Document Acknowledgements",
                "ordering": ["-acknowledged_at"],
                "unique_together": {("document", "employee")},
            },
        ),
    ]
