# Generated by Django 5.1.15 on 2026-03-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_portal", "0004_documentcategory_document_documentacknowledgement"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceQRToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("used_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Attendance QR Token",
                "verbose_name_plural": "Attendance QR Tokens",
                "ordering": ["-created_at"],
            },
        ),
    ]
