# Generated by Django 5.2.8 on 2026-08-21 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_emergencycontact_employeecontact_employmentdetails'),
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_days_entitled', models.IntegerField(default=20)),
                ('accrual_rate', models.DecimalField(decimal_places=2, default=1.67, max_digits=5)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_profile', to='hr.employees')),
            ],
            options={
                'db_table': 'leave_leaveprofile',
            },
        ),
    ]
