# Generated by Django 5.2.8 on 2026-08-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leaveprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='accrual_policy',
            field=models.CharField(choices=[('Annual', 'Granted in full at the start of the year'), ('Monthly', 'Accrues monthly')], default='Annual', max_length=20),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='accrual_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='is_statutory',
            field=models.BooleanField(default=False),
        ),
    ]
