# Generated by Django 5.2.3 on 2025-11-07 13:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("human_resources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyZiGRateToUSD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("average", models.DecimalField(decimal_places=8, max_digits=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Daily ZiG to USD Rate",
                "verbose_name_plural": "Daily ZiG to USD Rates",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PayrollPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Monthly, Bi-Weekly, Weekly",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "frequency_in_days",
                    models.IntegerField(
                        help_text="Number of days in the period (approximate for monthly, exact for others)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll Period Type",
                "verbose_name_plural": "Payroll Period Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TaxBracket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "USD"), ("ZiG", "ZiG")], max_length=10
                    ),
                ),
                ("min_income", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "max_income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leave blank for highest bracket",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=3, max_digits=5)),
                ("deduction", models.DecimalField(decimal_places=2, max_digits=10)),
                ("active_from", models.DateField(default=django.utils.timezone.now)),
                ("provider", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Tax Bracket",
                "verbose_name_plural": "Tax Brackets",
                "ordering": ["currency", "min_income", "-active_from"],
            },
        ),
        migrations.CreateModel(
            name="Payroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.DateField()),
                (
                    "base_salary_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "net_salary_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "base_salary_zig",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "net_salary_zig",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Pending", "Pending"),
                            ("Processed", "Processed"),
                            ("Failed", "Failed"),
                            ("Paid", "Paid"),
                        ],
                        default="Draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True)),
                (
                    "paye_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "paye_zig",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "aids_levy_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "aids_levy_zig",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "nssa_employee_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "nssa_employer_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "nssa_employee_zig",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "nssa_employer_zig",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_allowances_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_allowances_zig",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_deductions_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_deductions_zig",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payrolls",
                        to="human_resources.employees",
                    ),
                ),
            ],
            options={
                "ordering": ["-period", "employee__first_name"],
                "unique_together": {("employee", "period")},
            },
        ),
    ]
