# Generated by Django 5.2.3 on 2025-11-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollperiod",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="payrollperiod",
            name="start_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="payrollperiod",
            name="status",
            field=models.CharField(
                choices=[
                    ("Open", "Open"),
                    ("Processing", "Processing"),
                    ("Closed", "Closed"),
                ],
                default="Open",
                max_length=20,
            ),
        ),
    ]
