# Generated by Django 5.2.8 on 2026-03-24 13:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('qualifications', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'human_resources_candidate',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Draft', 'Draft'), ('Pending', 'Pending')], default='Open', max_length=20)),
                ('location', models.CharField(default='Harare', max_length=100)),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('salary_usd_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_usd_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_zig_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_zig_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reports_to', models.CharField(default='ZCHPC Director', max_length=200)),
                ('is_internal', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('responsibilities', models.JSONField(blank=True, default=list)),
                ('qualifications', models.JSONField(blank=True, default=list)),
                ('competencies', models.JSONField(blank=True, default=list)),
                ('application_process', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(default='hroffice@zchpc.ac.zw', max_length=254)),
                ('notes', models.TextField(blank=True, null=True)),
                ('posted_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.department')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_postings', to='hr.position')),
            ],
            options={
                'db_table': 'human_resources_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Shortlisted', 'Shortlisted'), ('Interview', 'Interview'), ('Offered', 'Offered'), ('Hired', 'Hired'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.job')),
            ],
            options={
                'db_table': 'human_resources_jobapplication',
                'ordering': ['-applied_on'],
                'unique_together': {('job', 'candidate')},
            },
        ),
    ]
