# Generated by Django 5.2.8 on 2026-03-24 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeepayrollconfig',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_config', to='hr.employees'),
        ),
        migrations.AddField(
            model_name='employeededuction',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='hr.employees'),
        ),
        migrations.AddField(
            model_name='employeeallowance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='hr.employees'),
        ),
        migrations.AddField(
            model_name='employeepayrollconfig',
            name='funeral_cover_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funeral_covers', to='hr.insuranceoption'),
        ),
        migrations.AddField(
            model_name='employeepayrollconfig',
            name='life_insurance_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='life_insurances', to='hr.insuranceoption'),
        ),
        migrations.AddField(
            model_name='employeepayrollconfig',
            name='medical_aid_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.medicalaidplan'),
        ),
        migrations.AddField(
            model_name='employeepayrollconfig',
            name='pension_fund_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.pensionfund'),
        ),
        migrations.AddField(
            model_name='position',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='hr.department'),
        ),
        migrations.AddField(
            model_name='employees',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.position'),
        ),
        migrations.AddField(
            model_name='employees',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='hr.role'),
        ),
        migrations.AddField(
            model_name='trainingcertification',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='hr.employees'),
        ),
        migrations.AddField(
            model_name='trainingenrollment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_enrollments', to='hr.employees'),
        ),
        migrations.AddField(
            model_name='trainingcertification',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.trainingprogram'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='hr.trainingprogram'),
        ),
        migrations.AddField(
            model_name='trainingenrollment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='hr.trainingsession'),
        ),
        migrations.AddField(
            model_name='employeepayrollconfig',
            name='union',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.union'),
        ),
        migrations.AlterUniqueTogether(
            name='employeededuction',
            unique_together={('employee', 'deduction_type')},
        ),
        migrations.AlterUniqueTogether(
            name='employeeallowance',
            unique_together={('employee', 'allowance_type')},
        ),
        migrations.AlterUniqueTogether(
            name='trainingenrollment',
            unique_together={('employee', 'session')},
        ),
        migrations.AlterUniqueTogether(
            name='employeepayrollconfig',
            unique_together={('employee', 'effective_date')},
        ),
    ]
