# Generated by Django 5.1.15 on 2026-03-29 21:22

import uuid
from django.db import migrations


def convert_employee_id_to_uuid(apps, schema_editor):
    Employee = apps.get_model('hr', 'Employees')
    db_alias = schema_editor.connection.alias
    for employee in Employee.objects.using(db_alias).all():
        if not employee.employee_id: # Handle empty or None
            employee.employee_id = str(uuid.uuid4())
        else:
            try:
                # Try to validate if it's already a UUID
                uuid.UUID(employee.employee_id)
            except ValueError:
                # If not a valid UUID, generate a new one
                employee.employee_id = str(uuid.uuid4())
        employee.save()

def revert_employee_id_to_char(apps, schema_editor):
    # This reverse operation is optional, but good practice.
    # We could convert back to a generic string or clear them.
    # For now, we'll leave it as is if we were to reverse.
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0003_alter_address_options_alter_allowancetype_options_and_more"),
    ]

    operations = [
        migrations.RunPython(convert_employee_id_to_uuid, revert_employee_id_to_char),
    ]
