# Generated by Django 5.1.15 on 2026-03-29 21:30

import uuid
from django.db import migrations, models


def fix_invalid_uuids_and_drop_index(apps, schema_editor):
    """Fix any invalid UUIDs and drop varchar_pattern_ops index."""
    Employee = apps.get_model('hr', 'Employees')
    db_alias = schema_editor.connection.alias

    # First, fix any invalid UUID values
    for employee in Employee.objects.using(db_alias).all():
        try:
            uuid.UUID(str(employee.employee_id))
        except (ValueError, TypeError):
            # Not a valid UUID, generate a new one
            employee.employee_id = str(uuid.uuid4())
            employee.save()

    # Then drop any incompatible indexes
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                SELECT indexname FROM pg_indexes
                WHERE tablename = 'hr_employees'
                AND indexdef LIKE '%varchar_pattern_ops%'
                AND indexdef LIKE '%employee_id%'
            """)
            for row in cursor.fetchall():
                cursor.execute(f'DROP INDEX IF EXISTS "{row[0]}"')


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0004_data_migration_employee_id_to_uuid"),
    ]

    operations = [
        migrations.RunPython(fix_invalid_uuids_and_drop_index, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="employees",
            name="employee_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
