# Generated by Django 5.1.15 on 2026-03-29 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0005_alter_employees_employee_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="employees",
            name="bank_account",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employees",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employees",
            name="contract_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employees",
            name="contract_to",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employees",
            name="date_joined",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employees",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employees",
            name="gender",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="employees",
            name="leave_days_entitled",
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name="employees",
            name="marital_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="employees",
            name="national_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employees",
            name="nssa_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employees",
            name="pay_frequency",
            field=models.CharField(default="monthly", max_length=20),
        ),
        migrations.AddField(
            model_name="employees",
            name="paye_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employees",
            name="pays_aids_levy",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="employees",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="employees",
            name="reports_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="direct_reports",
                to="hr.employees",
            ),
        ),
        migrations.AddField(
            model_name="employees",
            name="usd_salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="employees",
            name="zig_salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="employees",
            name="zimra_tax_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
