# Generated by Django 5.1.15 on 2026-03-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0006_add_employee_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="employees",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employees",
            name="emergency_contact_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="employees",
            name="emergency_contact_relationship",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employees",
            name="pension_fund",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
