# Generated by Django 5.1.15 on 2026-03-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0008_convert_employee_id_to_ec_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="allowancetype",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="allowancetype",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="allowancetype",
            name="is_taxable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="allowancetype",
            name="name",
            field=models.CharField(default="", max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name="deductiontype",
            name="default_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="deductiontype",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="deductiontype",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="deductiontype",
            name="is_percentage",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deductiontype",
            name="name",
            field=models.CharField(default="", max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name="allowancetype",
            table="hr_allowancetype",
        ),
        migrations.AlterModelTable(
            name="deductiontype",
            table="hr_deductiontype",
        ),
    ]
