# Generated by Django 5.2.8 on 2026-08-21 16:15

from django.db import migrations

def move_employee_data(apps, schema_editor):
    Employees = apps.get_model('hr', 'Employees')
    EmployeeContact = apps.get_model('hr', 'EmployeeContact')
    EmergencyContact = apps.get_model('hr', 'EmergencyContact')
    EmploymentDetails = apps.get_model('hr', 'EmploymentDetails')
    PayrollProfile = apps.get_model('payroll', 'PayrollProfile')
    EmployeeBankAccount = apps.get_model('payroll', 'EmployeeBankAccount')
    StatutoryProfile = apps.get_model('payroll', 'StatutoryProfile')
    LeaveProfile = apps.get_model('leave', 'LeaveProfile')

    for emp in Employees.objects.all():
        # 1. HR: EmployeeContact
        EmployeeContact.objects.create(
            employee=emp,
            personal_email=emp.email,
            phone=emp.phone
        )
        
        # 2. HR: EmergencyContact
        if emp.emergency_contact_name or emp.emergency_contact_number:
            EmergencyContact.objects.create(
                employee=emp,
                name=emp.emergency_contact_name or 'Unknown',
                relationship=emp.emergency_contact_relationship or 'Unknown',
                phone=emp.emergency_contact_number or 'Unknown'
            )
            
        # 3. HR: EmploymentDetails
        EmploymentDetails.objects.create(
            employee=emp,
            department=emp.department,
            position=emp.position,
            reports_to=emp.reports_to,
            date_joined=emp.date_joined,
            contract_from=emp.contract_from,
            contract_to=emp.contract_to,
            employee_type=emp.employee_type
        )
        
        # 4. Payroll: PayrollProfile
        PayrollProfile.objects.create(
            employee=emp,
            usd_salary=emp.usd_salary or 0.0,
            zig_salary=emp.zig_salary or 0.0,
            pay_frequency=emp.pay_frequency or 'monthly'
        )
        
        # 5. Payroll: EmployeeBankAccount
        if emp.bank_name or emp.bank_account:
            EmployeeBankAccount.objects.create(
                employee=emp,
                bank_name=emp.bank_name or 'Unknown Bank',
                account_number=emp.bank_account or 'Unknown Account'
            )
            
        # 6. Payroll: StatutoryProfile
        StatutoryProfile.objects.create(
            employee=emp,
            nssa_number=emp.nssa_number,
            zimra_tax_number=emp.zimra_tax_number,
            paye_number=emp.paye_number,
            pays_aids_levy=emp.pays_aids_levy,
            pension_fund=emp.pension_fund
        )
        
        # 7. Leave: LeaveProfile
        LeaveProfile.objects.create(
            employee=emp,
            leave_days_entitled=emp.leave_days_entitled
        )

def reverse_employee_data(apps, schema_editor):
    # Pass since data is stored in the new tables, and reversing will just drop those tables eventually anyway
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_emergencycontact_employeecontact_employmentdetails'),
        ('payroll', '0002_employeebankaccount_payrollprofile_statutoryprofile'),
        ('leave', '0002_leaveprofile'),
    ]

    operations = [
        migrations.RunPython(move_employee_data, reverse_employee_data),
    ]
