# Generated by Django 5.2.8 on 2026-08-21 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_move_employee_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='leave_days_entitled',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='nssa_number',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='pay_frequency',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='paye_number',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='pays_aids_levy',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='pension_fund',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='usd_salary',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='zig_salary',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='zimra_tax_number',
        ),
    ]
