# Generated by Django 5.2.8 on 2026-08-25 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_remove_employees_bank_account_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='EmployeePayrollConfig',
        ),
        migrations.DeleteModel(
            name='InsuranceOption',
        ),
        migrations.DeleteModel(
            name='MedicalAidPlan',
        ),
        migrations.DeleteModel(
            name='PensionFund',
        ),
        migrations.DeleteModel(
            name='TrainingCertification',
        ),
        migrations.DeleteModel(
            name='TrainingEnrollment',
        ),
        migrations.DeleteModel(
            name='TrainingProgram',
        ),
        migrations.DeleteModel(
            name='TrainingSession',
        ),
        migrations.DeleteModel(
            name='Union',
        ),
    ]
