# Generated by Django 5.2.8 on 2026-08-25 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_resync_employment_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='contract_from',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='contract_to',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='emergency_contact_number',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='emergency_contact_relationship',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='employee_type',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='position',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='reports_to',
        ),
    ]
