# Generated by Django 5.2.8 on 2026-08-31 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_default_orphaned_not_null_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeallowance',
            name='allowance_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='hr.allowancetype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeallowance',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeeallowance',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='employeeallowance',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='hr.employees'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeededuction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeededuction',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='employeededuction',
            name='deduction_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='hr.deductiontype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeededuction',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='hr.employees'),
            preserve_default=False,
        ),
    ]
