# Generated by Django 5.2.8 on 2026-09-12 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_employeeallowance_allowance_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, help_text='Employee accountable for this department (e.g. approves its requisitions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='hr.employees'),
        ),
    ]
