# Generated by Django 5.2.8 on 2026-08-27 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_remove_dead_stub_models'),
        ('hr', '0015_remove_employees_employment_inline_fields'),
    ]

    operations = [
    ]
