# Generated by Django 5.2.3 on 2025-06-17 07:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeductionType',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('mandatory', 'Mandatory'), ('optional', 'Optional')], max_length=20)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Deduction Type',
                'verbose_name_plural': 'Deduction Types',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(blank=True, max_length=10, unique=True)),
                ('firstname', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('nationalid', models.CharField(max_length=50, null=True, unique=True)),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('maritalStatus', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('position', models.CharField(max_length=50)),
                ('department', models.CharField(default='System', max_length=50)),
                ('employee_type', models.CharField(default='Unspecified', max_length=50)),
                ('leave_days', models.IntegerField(default=0)),
                ('contractFrom', models.DateField(blank=True, null=True)),
                ('contractTo', models.DateField(blank=True, null=True)),
                ('usd_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('zig_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('frequency', models.CharField(default='monthly', max_length=50)),
                ('bankName', models.CharField(blank=True, max_length=100)),
                ('bankAccount', models.CharField(blank=True, max_length=50)),
                ('pensionFund', models.CharField(blank=True, max_length=100)),
                ('nssaNumber', models.CharField(blank=True, max_length=50)),
                ('zimraTaxNumber', models.CharField(blank=True, max_length=50)),
                ('payeNumber', models.CharField(blank=True, max_length=50)),
                ('aidsLevyNumber', models.BooleanField(default=True)),
                ('isActive', models.BooleanField(default=True)),
                ('emegencyContactName', models.CharField(blank=True, max_length=100)),
                ('emegencyContactNumber', models.CharField(blank=True, max_length=15)),
                ('emegencyContactRelationship', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceOption',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('insurance_type', models.CharField(choices=[('funeral', 'Funeral Cover'), ('life', 'Life Insurance')], max_length=20)),
                ('calculation_type', models.CharField(blank=True, choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Salary')], max_length=30, null=True)),
                ('usd_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('zwl_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('min_amount_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_amount_zwl', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_amount_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_amount_zwl', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cover_details', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Insurance Option',
                'verbose_name_plural': 'Insurance Options',
            },
        ),
        migrations.CreateModel(
            name='MedicalAidProvider',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Medical Aid Provider',
                'verbose_name_plural': 'Medical Aid Providers',
            },
        ),
        migrations.CreateModel(
            name='PensionFund',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('employee_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('employer_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('currency', models.CharField(choices=[('usd', 'USD Only'), ('zwl', 'ZWL Only'), ('both', 'Both')], max_length=10)),
            ],
            options={
                'verbose_name': 'Pension Fund',
                'verbose_name_plural': 'Pension Funds',
            },
        ),
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('usd_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('zwl_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], max_length=20)),
            ],
            options={
                'verbose_name': 'Union',
                'verbose_name_plural': 'Unions',
            },
        ),
        migrations.CreateModel(
            name='ZiGRateToUSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'ZIG to USD Rate',
                'verbose_name_plural': 'ZIG to USD Rates',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('employeeid', models.CharField(blank=True, max_length=10, unique=True)),
                ('firstname', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('department', models.CharField(default='System', max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('contractFrom', models.DateField(blank=True, null=True)),
                ('contractTo', models.DateField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MedicalAidPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('usd_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('zwl_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.medicalaidprovider')),
            ],
            options={
                'verbose_name': 'Medical Aid Plan',
                'verbose_name_plural': 'Medical Aid Plans',
            },
        ),
        migrations.CreateModel(
            name='NSSACap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_cap', models.DecimalField(decimal_places=2, max_digits=10)),
                ('zwl_cap', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('contribution_type', models.CharField(choices=[('employee', 'Employee Only'), ('employer', 'Employer Only'), ('employee_and_employer', 'Employee and Employer')], max_length=30)),
                ('deduction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.deductiontype')),
            ],
            options={
                'verbose_name': 'NSSA Cap',
                'verbose_name_plural': 'NSSA Caps',
            },
        ),
        migrations.CreateModel(
            name='PAYETaxCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('zwl_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deduction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.deductiontype')),
            ],
            options={
                'verbose_name': 'PAYE Tax Credit',
                'verbose_name_plural': 'PAYE Tax Credits',
            },
        ),
        migrations.CreateModel(
            name='PAYEThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('ZWL', 'Zimbabwe Dollar')], max_length=3)),
                ('threshold_from', models.DecimalField(decimal_places=2, max_digits=12)),
                ('threshold_to', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('fixed_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deduction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.deductiontype')),
            ],
            options={
                'verbose_name': 'PAYE Threshold',
                'verbose_name_plural': 'PAYE Thresholds',
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('base_salary_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('net_salary_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('base_salary_zig', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('net_salary_zig', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Processed', 'Processed'), ('Failed', 'Failed'), ('Paid', 'Paid')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrolls', to='erp.employees')),
            ],
            options={
                'ordering': ['-period', 'employee__firstname'],
                'unique_together': {('employee', 'period')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeDeductables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('ZWL', 'Zimbabwe Dollar')], max_length=3)),
                ('pension_employee_contribution', models.BooleanField(default=True)),
                ('school_fees_benefit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('housing_benefit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loan_benefit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('effective_date', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.employees')),
                ('funeral_cover', models.ForeignKey(blank=True, limit_choices_to={'insurance_type': 'funeral'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funeral_cover', to='erp.insuranceoption')),
                ('life_insurance', models.ForeignKey(blank=True, limit_choices_to={'insurance_type': 'life'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='life_insurance', to='erp.insuranceoption')),
                ('medical_aid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.medicalaidplan')),
                ('pension_fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.pensionfund')),
                ('union', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.union')),
            ],
            options={
                'verbose_name': 'Employee Deductable',
                'verbose_name_plural': 'Employee Deductables',
                'unique_together': {('employee', 'effective_date')},
            },
        ),
    ]
