# Generated by Django 5.2.3 on 2025-08-22 19:50

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllowanceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
            ],
            options={
                "verbose_name": "Allowance Type",
                "verbose_name_plural": "Allowance Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DeductionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
            ],
            options={
                "verbose_name": "Deduction Type",
                "verbose_name_plural": "Deduction Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InsuranceOption",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "insurance_type",
                    models.CharField(
                        choices=[
                            ("funeral", "Funeral Cover"),
                            ("life", "Life Insurance"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "calculation_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fixed", "Fixed Amount"),
                            ("percentage", "Percentage of Salary"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "usd_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "zwl_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "min_amount_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "min_amount_zwl",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "max_amount_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "max_amount_zwl",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "cover_details",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "verbose_name": "Insurance Option",
                "verbose_name_plural": "Insurance Options",
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("department", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("requirements", models.TextField()),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "salary_range",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("posted_on", models.DateTimeField(auto_now_add=True)),
                ("applicants_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="MedicalAidProvider",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Medical Aid Provider",
                "verbose_name_plural": "Medical Aid Providers",
            },
        ),
        migrations.CreateModel(
            name="PayrollPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Monthly, Bi-Weekly, Weekly",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "frequency_in_days",
                    models.IntegerField(
                        help_text="Number of days in the period (approximate for monthly, exact for others)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll Period Type",
                "verbose_name_plural": "Payroll Period Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PensionFund",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("employee_rate", models.DecimalField(decimal_places=4, max_digits=5)),
                ("employer_rate", models.DecimalField(decimal_places=4, max_digits=5)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("usd", "USD Only"),
                            ("zwl", "ZWL Only"),
                            ("both", "Both"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pension Fund",
                "verbose_name_plural": "Pension Funds",
            },
        ),
        migrations.CreateModel(
            name="TaxBracket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "USD"), ("ZWG", "ZWL/ZiG")], max_length=10
                    ),
                ),
                ("min_income", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "max_income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leave blank for highest bracket",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=3, max_digits=5)),
                ("deduction", models.DecimalField(decimal_places=2, max_digits=10)),
                ("active_from", models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Tax Bracket",
                "verbose_name_plural": "Tax Brackets",
                "ordering": ["currency", "min_income", "-active_from"],
            },
        ),
        migrations.CreateModel(
            name="TrainingCertification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee", models.CharField(max_length=100)),
                ("program", models.CharField(max_length=100)),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Valid", "Valid"),
                            ("Expired", "Expired"),
                            ("Pending", "Pending"),
                        ],
                        default="Valid",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainingEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee", models.CharField(max_length=200)),
                ("program", models.CharField(max_length=200)),
                ("session_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Enrolled", "Enrolled"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                        ],
                        default="Enrolled",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("duration", models.CharField(blank=True, max_length=50, null=True)),
                ("mandatory", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("program", models.CharField(max_length=200)),
                ("trainer", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("venue", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Scheduled", "Scheduled"),
                            ("Ongoing", "Ongoing"),
                            ("Completed", "Completed"),
                        ],
                        default="Scheduled",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Union",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("usd_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("zwl_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "frequency",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("annual", "Annual")],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Union",
                "verbose_name_plural": "Unions",
            },
        ),
        migrations.CreateModel(
            name="ZiGRateToUSD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
            ],
            options={
                "verbose_name": "ZIG to USD Rate",
                "verbose_name_plural": "ZIG to USD Rates",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        default="c20adf48bbe74f74b1e157275541c70f",
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "employeeid",
                    models.CharField(blank=True, max_length=10, unique=True),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("HR", "HR"),
                            ("ACCOUNTANT", "Accountant"),
                            ("PROCUREMENT", "Procurement"),
                            ("SALES", "Sales"),
                            ("MANAGER", "Manager"),
                            ("STAFF", "Staff"),
                            ("INTERN", "Intern"),
                        ],
                        max_length=50,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("salary", models.IntegerField(blank=True, null=True)),
                ("contractFrom", models.DateField(blank=True, null=True)),
                ("contractTo", models.DateField(blank=True, null=True)),
                ("isActive", models.BooleanField(default=True)),
                ("failed_attempts", models.IntegerField(default=0)),
                ("lockout_until", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "department_head",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="headed_departments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="erp.department",
            ),
        ),
        migrations.CreateModel(
            name="Employees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employeeid",
                    models.CharField(blank=True, max_length=10, unique=True),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                ("nationalid", models.CharField(max_length=50, null=True, unique=True)),
                ("dateOfBirth", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=50)),
                ("maritalStatus", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=15)),
                ("position", models.CharField(max_length=50)),
                ("department", models.CharField(default="System", max_length=50)),
                (
                    "employee_type",
                    models.CharField(default="Unspecified", max_length=50),
                ),
                ("leave_days", models.IntegerField(default=0)),
                ("contractFrom", models.DateField(blank=True, null=True)),
                ("contractTo", models.DateField(blank=True, null=True)),
                (
                    "usd_salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "zig_salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("frequency", models.CharField(default="monthly", max_length=50)),
                ("bankName", models.CharField(blank=True, max_length=100)),
                ("bankAccount", models.CharField(blank=True, max_length=50)),
                ("pensionFund", models.CharField(blank=True, max_length=100)),
                ("nssaNumber", models.CharField(blank=True, max_length=50)),
                ("zimraTaxNumber", models.CharField(blank=True, max_length=50)),
                ("payeNumber", models.CharField(blank=True, max_length=50)),
                ("aidsLevyNumber", models.BooleanField(default=True)),
                ("isActive", models.BooleanField(default=True)),
                ("emegencyContactName", models.CharField(blank=True, max_length=100)),
                ("emegencyContactNumber", models.CharField(blank=True, max_length=15)),
                (
                    "emegencyContactRelationship",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "allowances",
                    models.ManyToManyField(
                        blank=True,
                        related_name="employees_with_allowance",
                        to="erp.allowancetype",
                    ),
                ),
                (
                    "deductions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="employees_with_deduction",
                        to="erp.deductiontype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoginAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username_attempted", models.CharField(max_length=150)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Login Success"),
                            ("FAILED", "Login Failed"),
                            ("LOCKOUT", "Account Locked"),
                            ("FORCE_RESET", "Forced Password Reset"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Login Audit Log",
                "verbose_name_plural": "Login Audit Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="MedicalAidPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("usd_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("zwl_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp.medicalaidprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medical Aid Plan",
                "verbose_name_plural": "Medical Aid Plans",
            },
        ),
        migrations.CreateModel(
            name="NSSACap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usd_cap", models.DecimalField(decimal_places=2, max_digits=10)),
                ("zwl_cap", models.DecimalField(decimal_places=2, max_digits=12)),
                ("rate", models.DecimalField(decimal_places=4, max_digits=5)),
                (
                    "contribution_type",
                    models.CharField(
                        choices=[
                            ("employee", "Employee Only"),
                            ("employer", "Employer Only"),
                            ("employee_and_employer", "Employee and Employer"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "deduction_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp.deductiontype",
                    ),
                ),
            ],
            options={
                "verbose_name": "NSSA Cap",
                "verbose_name_plural": "NSSA Caps",
            },
        ),
        migrations.CreateModel(
            name="PAYETaxCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usd_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("zwl_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "deduction_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp.deductiontype",
                    ),
                ),
            ],
            options={
                "verbose_name": "PAYE Tax Credit",
                "verbose_name_plural": "PAYE Tax Credits",
            },
        ),
        migrations.CreateModel(
            name="PAYEThreshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "US Dollar"), ("ZWL", "Zimbabwe Dollar")],
                        max_length=3,
                    ),
                ),
                (
                    "threshold_from",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("threshold_to", models.DecimalField(decimal_places=2, max_digits=12)),
                ("rate", models.DecimalField(decimal_places=4, max_digits=5)),
                ("fixed_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "deduction_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp.deductiontype",
                    ),
                ),
            ],
            options={
                "verbose_name": "PAYE Threshold",
                "verbose_name_plural": "PAYE Thresholds",
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time_in", models.TimeField(blank=True, null=True)),
                ("time_out", models.TimeField(blank=True, null=True)),
                ("job_number", models.CharField(blank=True, max_length=50)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "employee__first_name"],
                "unique_together": {("employee", "date")},
            },
        ),
        migrations.CreateModel(
            name="Payroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.DateField()),
                (
                    "base_salary_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "net_salary_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "base_salary_zig",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "net_salary_zig",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Pending", "Pending"),
                            ("Processed", "Processed"),
                            ("Failed", "Failed"),
                            ("Paid", "Paid"),
                        ],
                        default="Draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True)),
                (
                    "nssa_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "pension_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "nssa_zig",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "pension_zig",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payrolls",
                        to="erp.employees",
                    ),
                ),
            ],
            options={
                "ordering": ["-period", "employee__firstname"],
                "unique_together": {("employee", "period")},
            },
        ),
        migrations.CreateModel(
            name="EmployeeDeductables",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "US Dollar"), ("ZWL", "Zimbabwe Dollar")],
                        max_length=3,
                    ),
                ),
                ("pension_employee_contribution", models.BooleanField(default=True)),
                (
                    "school_fees_benefit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "housing_benefit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "loan_benefit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("active", models.BooleanField(default=True)),
                ("effective_date", models.DateField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="erp.employees"
                    ),
                ),
                (
                    "funeral_cover",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"insurance_type": "funeral"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="funeral_cover",
                        to="erp.insuranceoption",
                    ),
                ),
                (
                    "life_insurance",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"insurance_type": "life"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="life_insurance",
                        to="erp.insuranceoption",
                    ),
                ),
                (
                    "medical_aid",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="erp.medicalaidplan",
                    ),
                ),
                (
                    "pension_fund",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="erp.pensionfund",
                    ),
                ),
                (
                    "union",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="erp.union",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Deductable",
                "verbose_name_plural": "Employee Deductables",
                "unique_together": {("employee", "effective_date")},
            },
        ),
    ]
