# Generated by Django 5.2.3 on 2025-08-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.CharField(
                default="7f60988a6966486485958ab7d52c74e9",
                editable=False,
                max_length=32,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
