# Generated by Django 5.2.3 on 2025-08-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0002_alter_customuser_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LoginAuditLog",
            new_name="AuditLog",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.CharField(
                default="2477c3fa75f244e1bd392d21787e1163",
                editable=False,
                max_length=32,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
