# Generated by Django 5.2.3 on 2025-07-11 16:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_payroll_nssa_usd_payroll_nssa_zig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('ZWG', 'ZWL/ZiG')], max_length=10)),
                ('min_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_income', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for highest bracket', max_digits=10, null=True)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=5)),
                ('deduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active_from', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Tax Bracket',
                'verbose_name_plural': 'Tax Brackets',
                'ordering': ['currency', 'min_income', '-active_from'],
            },
        ),
    ]
