# Generated by Django 5.2.3 on 2025-07-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_taxbracket'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Monthly, Bi-Weekly, Weekly', max_length=100, unique=True)),
                ('frequency_in_days', models.IntegerField(help_text='Number of days in the period (approximate for monthly, exact for others)')),
            ],
            options={
                'verbose_name': 'Payroll Period Type',
                'verbose_name_plural': 'Payroll Period Types',
                'ordering': ['name'],
            },
        ),
    ]
