# Generated by Django 5.2.3 on 2025-09-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0003_rename_loginauditlog_auditlog_alter_customuser_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="salary",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.CharField(
                default="614afba26a9d446eb745bfd0489ab6e6",
                editable=False,
                max_length=32,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="taxbracket",
            name="currency",
            field=models.CharField(
                choices=[("USD", "USD"), ("ZiG", "ZiG")], max_length=10
            ),
        ),
    ]
