# Generated by Django 5.2.3 on 2025-07-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_payrollperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Allowance Type',
                'verbose_name_plural': 'Allowance Types',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='deductiontype',
            options={'ordering': ['name'], 'verbose_name': 'Deduction Type', 'verbose_name_plural': 'Deduction Types'},
        ),
        migrations.RemoveField(
            model_name='deductiontype',
            name='type',
        ),
        migrations.AddField(
            model_name='deductiontype',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employees',
            name='deductions',
            field=models.ManyToManyField(blank=True, related_name='employees_with_deduction', to='erp.deductiontype'),
        ),
        migrations.AlterField(
            model_name='deductiontype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deductiontype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deductiontype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='allowances',
            field=models.ManyToManyField(blank=True, related_name='employees_with_allowance', to='erp.allowancetype'),
        ),
    ]
