# Generated by Django 5.2.3 on 2025-09-01 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0004_remove_customuser_salary_alter_customuser_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.CharField(
                default="d7a7aaf377734dd79fd60779230f0415",
                editable=False,
                max_length=32,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
