# Generated by Django 5.2.3 on 2025-09-02 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0005_customuser_salary_alter_customuser_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="nssacap",
            name="active_from",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="payroll",
            name="tax_usd",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="payroll",
            name="tax_zig",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.CharField(
                default="f4a0ea80775f432a99f29f48040de428",
                editable=False,
                max_length=32,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
