# Generated by Django 5.2.3 on 2025-09-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0006_nssacap_active_from_payroll_tax_usd_payroll_tax_zig_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyZiGRateToUSD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("average", models.DecimalField(decimal_places=8, max_digits=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Daily ZiG to USD Rate",
                "verbose_name_plural": "Daily ZiG to USD Rates",
                "ordering": ["-date"],
            },
        ),
        migrations.DeleteModel(
            name="ZiGRateToUSD",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.CharField(
                default="cb649dd8eca24e6e8052ca146382b55e",
                editable=False,
                max_length=32,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
