# Generated by Django 5.2.4 on 2025-08-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_trainingprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=200)),
                ('trainer', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
