# Generated by Django 5.2.4 on 2025-08-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_trainingsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=200)),
                ('program', models.CharField(max_length=200)),
                ('session_date', models.DateField()),
                ('status', models.CharField(choices=[('Enrolled', 'Enrolled'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Enrolled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
