# Generated by Django 5.2.3 on 2025-09-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0007_dailyzigratetousd_delete_zigratetousd_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payroll",
            old_name="tax_usd",
            new_name="aids_levy_usd",
        ),
        migrations.RenameField(
            model_name="payroll",
            old_name="tax_zig",
            new_name="aids_levy_zig",
        ),
        migrations.RemoveField(
            model_name="payroll",
            name="nssa_usd",
        ),
        migrations.RemoveField(
            model_name="payroll",
            name="nssa_zig",
        ),
        migrations.RemoveField(
            model_name="payroll",
            name="pension_usd",
        ),
        migrations.RemoveField(
            model_name="payroll",
            name="pension_zig",
        ),
        migrations.AddField(
            model_name="payroll",
            name="nssa_employee_usd",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="payroll",
            name="nssa_employee_zig",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="payroll",
            name="nssa_employer_usd",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="payroll",
            name="nssa_employer_zig",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="payroll",
            name="paye_usd",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="payroll",
            name="paye_zig",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="payroll",
            name="total_allowances_usd",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="payroll",
            name="total_allowances_zig",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="payroll",
            name="total_deductions_usd",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="payroll",
            name="total_deductions_zig",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="taxbracket",
            name="provider",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.CharField(
                default="235a58a6933b4670a85ad6a8048787fc",
                editable=False,
                max_length=32,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
