# Generated by Django 5.2.4 on 2025-08-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_trainingenrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('Valid', 'Valid'), ('Expired', 'Expired'), ('Pending', 'Pending')], default='Valid', max_length=10)),
            ],
        ),
    ]
