# Generated by Django 5.2.4 on 2025-08-07 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_certification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certification',
            new_name='TrainingCertification',
        ),
    ]
