# Generated by Django 5.2.8 on 2026-08-24 08:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_add_deduction_allowance_fields'),
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.CharField(blank=True, max_length=255)),
                ('recipient_driver', models.CharField(max_length=255)),
                ('requester_signature', models.CharField(blank=True, max_length=255)),
                ('vehicle_registration', models.CharField(max_length=50)),
                ('request_date', models.DateField(default=django.utils.timezone.now)),
                ('diesel_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('petrol_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('purpose', models.TextField()),
                ('destination', models.CharField(max_length=255)),
                ('finance_recommendation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING_DEPARTMENT', 'Pending Department'), ('PENDING_FINANCE', 'Pending Finance / General Manager'), ('PENDING_DIRECTOR', 'Pending Director'), ('PENDING_ADMIN', 'Pending Administration'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_DEPARTMENT', max_length=30)),
                ('rejection_reason', models.TextField(blank=True)),
                ('department_approved_at', models.DateTimeField(blank=True, null=True)),
                ('finance_approved_at', models.DateTimeField(blank=True, null=True)),
                ('director_approved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_approved_at', models.DateTimeField(blank=True, null=True)),
                ('issuance_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('serial_numbers', models.CharField(blank=True, max_length=255)),
                ('issued_by_name', models.CharField(blank=True, max_length=255)),
                ('received_by_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_fuel_approvals', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.department')),
                ('department_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_fuel_approvals', to=settings.AUTH_USER_MODEL)),
                ('director_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='director_fuel_approvals', to=settings.AUTH_USER_MODEL)),
                ('finance_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_fuel_approvals', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_requisitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
