# Generated by Django 5.2.8 on 2026-08-25 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_fuelrequisition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelrequisition',
            name='recipient_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuelrequisition',
            name='recipient_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipient_fuel_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fuelrequisition',
            name='status',
            field=models.CharField(choices=[('PENDING_DEPARTMENT', 'Pending Department'), ('PENDING_RECIPIENT', 'Pending Recipient / Driver'), ('PENDING_FINANCE', 'Pending Finance / General Manager'), ('PENDING_DIRECTOR', 'Pending Director'), ('PENDING_ADMIN', 'Pending Administration'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_DEPARTMENT', max_length=30),
        ),
    ]
