# Generated by Django 5.2.8 on 2026-08-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_fuelrequisition_recipient_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelrequisition',
            name='destination_dates',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='fuelrequisition',
            name='diesel_quantity_words',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='fuelrequisition',
            name='petrol_quantity_words',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
