# Generated by Django 5.2.8 on 2026-08-25 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_add_deduction_allowance_fields'),
        ('procurement', '0004_fuelrequisition_destination_dates_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoresRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('items', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('PENDING_DEPARTMENT', 'Pending Head of Department'), ('PENDING_PROCUREMENT', 'Pending Procurement / Stores'), ('PENDING_ACCOUNTS', 'Pending Accounts / Finance'), ('PENDING_GENERAL_MANAGER', 'Pending General Manager'), ('PENDING_DIRECTOR', 'Pending Director'), ('PENDING_ADMIN', 'Pending Administration'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_DEPARTMENT', max_length=30)),
                ('rejection_reason', models.TextField(blank=True)),
                ('department_approved_at', models.DateTimeField(blank=True, null=True)),
                ('procurement_approved_at', models.DateTimeField(blank=True, null=True)),
                ('accounts_approved_at', models.DateTimeField(blank=True, null=True)),
                ('general_manager_approved_at', models.DateTimeField(blank=True, null=True)),
                ('director_approved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounts_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_stores_approvals', to=settings.AUTH_USER_MODEL)),
                ('admin_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_stores_approvals', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.department')),
                ('department_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_stores_approvals', to=settings.AUTH_USER_MODEL)),
                ('director_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='director_stores_approvals', to=settings.AUTH_USER_MODEL)),
                ('general_manager_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='general_manager_stores_approvals', to=settings.AUTH_USER_MODEL)),
                ('procurement_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_stores_approvals', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores_requisitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
