# Generated by Django 5.2.8 on 2026-08-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_storesrequisition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesrequisition',
            name='status',
            field=models.CharField(choices=[('PENDING_DEPARTMENT', 'Pending Head of Department'), ('PENDING_PROCUREMENT', 'Pending Procurement'), ('PENDING_ACCOUNTS', 'Pending Accounts'), ('PENDING_GENERAL_MANAGER', 'Pending General Manager'), ('PENDING_DIRECTOR', 'Pending Director'), ('PENDING_ADMIN', 'Pending Admin'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_DEPARTMENT', max_length=30),
        ),
    ]
