# Generated by Django 5.2.8 on 2026-08-25 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_alter_storesrequisition_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparativeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('compliance', models.JSONField(default=dict)),
                ('items', models.JSONField(default=list)),
                ('recommendation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING_DIRECTOR', 'Pending Director'), ('PENDING_PROCUREMENT', 'Pending Procurement'), ('PENDING_ACCOUNTS', 'Pending Accounts'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_DIRECTOR', max_length=30)),
                ('rejection_reason', models.TextField(blank=True)),
                ('procurement_submitted_at', models.DateTimeField(auto_now_add=True)),
                ('director_approved_at', models.DateTimeField(blank=True, null=True)),
                ('procurement_finalised_at', models.DateTimeField(blank=True, null=True)),
                ('accounts_approved_at', models.DateTimeField(blank=True, null=True)),
                ('accounts_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_comparative_approvals', to=settings.AUTH_USER_MODEL)),
                ('director_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='director_comparative_approvals', to=settings.AUTH_USER_MODEL)),
                ('procurement_finalised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='final_procurement_comparative_approvals', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comparative_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-procurement_submitted_at'],
            },
        ),
    ]
