# Generated by Django 5.2.8 on 2026-09-14 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountchart_external_account_type'),
        ('procurement', '0008_redesign_purchase_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Employee-facing label, e.g. "IT Consumables" - not a GL account name', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive categories are kept (for historical requests) but cannot be selected for new ones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_chart', models.OneToOneField(help_text='The single AccountChart row this category resolves to', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request_category', to='accounts.accountchart')),
            ],
            options={
                'verbose_name_plural': 'Purchase request categories',
                'db_table': 'procurement_purchaserequestcategory',
                'ordering': ['name'],
            },
        ),
    ]
