# Generated by Django 5.2.8 on 2026-09-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0018_seed_purchase_request_permissions'),
        ('procurement', '0009_purchaserequestcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='purchase_order_number',
            field=models.CharField(blank=True, help_text='Manually entered by Procurement at processing time (F23) - not auto-generated', max_length=50, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['purchase_order_number'], name='pr_po_number_idx'),
        ),
    ]
