# Generated by Django 5.2.3 on 2025-11-07 13:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'Headquarters', 'Warehouse'",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("street", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                (
                    "state",
                    models.CharField(max_length=100, verbose_name="State/Province"),
                ),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.CreateModel(
            name="AllowanceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "resume",
                    models.FileField(blank=True, null=True, upload_to="resumes/"),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DeductionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InsuranceOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=100)),
                ("plan_name", models.CharField(max_length=100)),
                (
                    "insurance_type",
                    models.CharField(
                        choices=[("funeral", "Funeral"), ("life", "Life")],
                        max_length=20,
                    ),
                ),
                (
                    "employee_contribution",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "company_contribution",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("default_days_allowed", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="MedicalAidPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=100)),
                ("plan_name", models.CharField(max_length=100)),
                (
                    "employee_contribution",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "company_contribution",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PensionFund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=100)),
                ("plan_name", models.CharField(max_length=100)),
                (
                    "employee_contribution_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        help_text="Percentage (e.g., 5.0 for 5%)",
                        max_digits=5,
                    ),
                ),
                (
                    "company_contribution_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        help_text="Percentage (e.g., 5.0 for 5%)",
                        max_digits=5,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainingProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        help_text="e.g., '3 Days', '2 Hours'",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("mandatory", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Union",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "dues_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated (e.g., EMP0001)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "employee_type",
                    models.CharField(
                        choices=[
                            ("Full-time", "Full-time"),
                            ("Part-time", "Part-time"),
                            ("Contract", "Contract"),
                            ("Intern", "Intern"),
                        ],
                        default="Full-time",
                        max_length=50,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="National ID",
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Single", "Single"),
                            ("Married", "Married"),
                            ("Divorced", "Divorced"),
                            ("Widowed", "Widowed"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Work or personal email", max_length=254, unique=True
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=15)),
                ("date_joined", models.DateField(default=django.utils.timezone.now)),
                ("contract_from", models.DateField(blank=True, null=True)),
                ("contract_to", models.DateField(blank=True, null=True)),
                (
                    "leave_days_entitled",
                    models.IntegerField(
                        default=22, verbose_name="Annual Leave Days Entitled"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "usd_salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "zig_salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "pay_frequency",
                    models.CharField(
                        choices=[
                            ("Monthly", "Monthly"),
                            ("Weekly", "Weekly"),
                            ("Bi-Weekly", "Bi-Weekly"),
                        ],
                        default="Monthly",
                        max_length=50,
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("bank_account", models.CharField(blank=True, max_length=50)),
                ("pension_fund", models.CharField(blank=True, max_length=100)),
                (
                    "nssa_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="NSSA Number"
                    ),
                ),
                (
                    "zimra_tax_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ZIMRA Tax Number"
                    ),
                ),
                (
                    "paye_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="PAYE Number"
                    ),
                ),
                (
                    "pays_aids_levy",
                    models.BooleanField(default=True, verbose_name="Pays AIDS Levy"),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "emergency_contact_number",
                    models.CharField(blank=True, max_length=15),
                ),
                (
                    "emergency_contact_relationship",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="human_resources.department",
                    ),
                ),
                (
                    "reports_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="direct_reports",
                        to="human_resources.employees",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employees",
                "verbose_name_plural": "Employees",
                "ordering": ["surname", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("requirements", models.TextField()),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "salary_range",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("posted_on", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="human_resources.department",
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_on"],
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("requested_on", models.DateTimeField(auto_now_add=True)),
                ("review_date", models.DateTimeField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="human_resources.employees",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_leave_requests",
                        to="human_resources.employees",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="human_resources.leavetype",
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_on"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="human_resources.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Position",
                "verbose_name_plural": "Positions",
                "ordering": ["department", "title"],
            },
        ),
        migrations.AddField(
            model_name="employees",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="human_resources.position",
            ),
        ),
        migrations.CreateModel(
            name="TrainingCertification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certification_name", models.CharField(max_length=200)),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="human_resources.employees",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="human_resources.trainingprogram",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trainer", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("venue", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Scheduled", "Scheduled"),
                            ("Ongoing", "Ongoing"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="human_resources.trainingprogram",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeDeduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "deduction_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="human_resources.deductiontype",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deductions",
                        to="human_resources.employees",
                    ),
                ),
            ],
            options={
                "unique_together": {("employee", "deduction_type")},
            },
        ),
        migrations.CreateModel(
            name="EmployeeAllowance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "allowance_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="human_resources.allowancetype",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowances",
                        to="human_resources.employees",
                    ),
                ),
            ],
            options={
                "unique_together": {("employee", "allowance_type")},
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time_in", models.TimeField(blank=True, null=True)),
                ("time_out", models.TimeField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="human_resources.employees",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "employee__first_name"],
                "unique_together": {("employee", "date")},
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applied_on", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Shortlisted", "Shortlisted"),
                            ("Interview", "Interview"),
                            ("Offered", "Offered"),
                            ("Hired", "Hired"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="human_resources.candidate",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="human_resources.job",
                    ),
                ),
            ],
            options={
                "ordering": ["-applied_on"],
                "unique_together": {("job", "candidate")},
            },
        ),
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(default=2025)),
                ("days_remaining", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to="human_resources.employees",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="human_resources.leavetype",
                    ),
                ),
            ],
            options={
                "unique_together": {("employee", "leave_type", "year")},
            },
        ),
        migrations.CreateModel(
            name="TrainingEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Enrolled", "Enrolled"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                            ("Dropped", "Dropped"),
                        ],
                        default="Enrolled",
                        max_length=20,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_enrollments",
                        to="human_resources.employees",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="human_resources.trainingsession",
                    ),
                ),
            ],
            options={
                "unique_together": {("employee", "session")},
            },
        ),
        migrations.CreateModel(
            name="EmployeePayrollConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "US Dollar"), ("ZIG", "Zimbabwean Gold")],
                        default="USD",
                        max_length=3,
                    ),
                ),
                (
                    "school_fees_benefit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "housing_benefit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "loan_benefit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("effective_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_config",
                        to="human_resources.employees",
                    ),
                ),
                (
                    "funeral_cover_plan",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"insurance_type": "funeral"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="funeral_covers",
                        to="human_resources.insuranceoption",
                    ),
                ),
                (
                    "life_insurance_plan",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"insurance_type": "life"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="life_insurances",
                        to="human_resources.insuranceoption",
                    ),
                ),
                (
                    "medical_aid_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="human_resources.medicalaidplan",
                    ),
                ),
                (
                    "pension_fund_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="human_resources.pensionfund",
                    ),
                ),
                (
                    "union",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="human_resources.union",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employees Payroll Config",
                "verbose_name_plural": "Employees Payroll Configs",
                "unique_together": {("employee", "effective_date")},
            },
        ),
    ]
