# Generated by Django 5.2.3 on 2025-11-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human_resources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employees",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("HR", "HR"),
                    ("ACCOUNTANT", "Accountant"),
                    ("PROCUREMENT", "Procurement"),
                    ("SALES", "Sales"),
                    ("MANAGER", "Manager"),
                    ("STAFF", "Staff"),
                    ("INTERN", "Intern"),
                ],
                default="STAFF",
                max_length=50,
            ),
        ),
    ]
