# Generated by Django 5.2.8 on 2025-12-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human_resources", "0002_role_alter_employees_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
