# Generated by Django 5.2.8 on 2025-11-21 06:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human_resources", "0003_alter_employees_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employees",
            name="date_joined",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
