# Generated by Django 5.2.8 on 2026-01-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human_resources", "0003_role_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leavebalance",
            name="year",
            field=models.IntegerField(default=2026),
        ),
    ]
