# Generated by Django 5.2.8 on 2026-01-12 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human_resources", "0004_alter_leavebalance_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="competencies",
            field=models.JSONField(
                blank=True, default=list, help_text="Required competencies for the role"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="is_internal",
            field=models.BooleanField(
                default=False, help_text="If True, only visible to internal staff"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="job_postings",
                to="human_resources.position",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="reports_to",
            field=models.CharField(
                default="ZCHPC Director",
                help_text="Who this position reports to",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
