# Generated by Django 5.2.3 on 2025-11-21 13:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human_resources", "0004_alter_employees_date_joined"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="job",
            old_name="posted_on",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="job",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="job",
            name="requirements",
        ),
        migrations.AddField(
            model_name="job",
            name="application_process",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="contact_email",
            field=models.EmailField(default="hroffice@zchpc.ac.zw", max_length=254),
        ),
        migrations.AddField(
            model_name="job",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="posted_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name="job",
            name="qualifications",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="job",
            name="responsibilities",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("Open", "Open"),
                    ("Closed", "Closed"),
                    ("Draft", "Draft"),
                    ("Pending", "Pending"),
                ],
                default="Open",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.TextField(blank=True, help_text="General summary"),
        ),
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.CharField(default="Harare", max_length=100),
        ),
    ]
