# Generated by Django 5.2.8 on 2026-03-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "human_resources",
            "0005_job_competencies_job_is_internal_job_position_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="salary_usd_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="salary_usd_min",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="salary_zig_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="salary_zig_min",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
