# Generated by Django 5.1.15 on 2026-03-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human_resources", "0006_job_salary_usd_max_job_salary_usd_min_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeallowance",
            name="currency",
            field=models.CharField(
                choices=[("USD", "US Dollar"), ("ZIG", "Zimbabwean Gold")],
                default="USD",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="employeededuction",
            name="currency",
            field=models.CharField(
                choices=[("USD", "US Dollar"), ("ZIG", "Zimbabwean Gold")],
                default="USD",
                max_length=3,
            ),
        ),
    ]
