# Generated by Django 5.1.15 on 2026-03-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human_resources", "0007_add_currency_to_allowances_deductions"),
    ]

    operations = [
        migrations.AddField(
            model_name="allowancetype",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Default amount for this allowance type",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="deductiontype",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Default amount for this deduction type",
                max_digits=10,
            ),
        ),
    ]
