# Generated by Django 5.1.15 on 2026-03-02 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human_resources", "0008_add_amount_to_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("Holiday", "Public Holiday"),
                            ("Company", "Company Event"),
                            ("Meeting", "Meeting"),
                            ("Training", "Training"),
                            ("Other", "Other"),
                        ],
                        default="Company",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("is_all_day", models.BooleanField(default=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_events",
                        to="human_resources.employees",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date", "start_time"],
            },
        ),
    ]
