# Generated by Django 5.1.15 on 2026-03-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human_resources", "0009_add_company_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="experience",
            field=models.TextField(blank=True, help_text="Work experience summary"),
        ),
        migrations.AddField(
            model_name="candidate",
            name="id_number",
            field=models.CharField(
                blank=True,
                help_text="National ID number - used to prevent duplicate applications",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="qualifications",
            field=models.TextField(blank=True, help_text="Educational qualifications"),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="cover_letter",
            field=models.TextField(blank=True, help_text="Cover letter or motivation"),
        ),
    ]
