# Generated by Django 5.2.8 on 2026-08-25 07:20, hand-edited to backfill
# tag_ids -> tags before dropping the old column (expand-migrate-contract).

from django.db import migrations, models


def backfill_tags_from_tag_ids(apps, schema_editor):
    AccountMoveLine = apps.get_model('accounts', 'AccountMoveLine')
    AccountTag = apps.get_model('accounts', 'AccountTag')
    for line in AccountMoveLine.objects.exclude(tag_ids=[]):
        tags = AccountTag.objects.filter(pk__in=line.tag_ids)
        line.tags.set(tags)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmoveline',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='move_lines', to='accounts.accounttag'),
        ),
        migrations.RunPython(backfill_tags_from_tag_ids, noop_reverse),
        migrations.RemoveField(
            model_name='accountmoveline',
            name='tag_ids',
        ),
    ]
