# Generated by Django 5.2.8 on 2026-09-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountchart',
            name='external_account_type',
            field=models.CharField(blank=True, default='', help_text='Account type exactly as exported by the external accounting system', max_length=100),
        ),
    ]
