# Generated by Django 5.2.8 on 2026-06-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=False)),
                ('dependencies', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'System Module',
                'verbose_name_plural': 'System Modules',
                'db_table': 'identity_systemmodule',
            },
        ),
    ]
