# Generated by Django 5.2.8 on 2026-09-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_seed_core_system_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
