# Generated by Django 5.2.8 on 2026-09-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('leave_request', 'New Leave Request'), ('expense_approved', 'Expense Approved'), ('expense_rejected', 'Expense Rejected'), ('ticket_update', 'Ticket Update'), ('ticket_resolved', 'Ticket Resolved'), ('payslip_available', 'Payslip Available'), ('announcement', 'Announcement'), ('system', 'System Notification'), ('purchase_request_rejected', 'Purchase Request Rejected'), ('purchase_request_processed', 'Purchase Request Processed')], max_length=50),
        ),
    ]
