# Generated by Django 5.2.8 on 2026-09-29 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('document_type', models.CharField(help_text='E.g. procurement.PurchaseRequest - the governed record.', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('state_field', models.CharField(default='status', help_text='Record attribute holding the current state value.', max_length=64)),
            ],
            options={
                'db_table': 'workflow_workflow',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('document_type',), name='one_active_workflow_per_doctype')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Machine name, e.g. approve.', max_length=64)),
                ('label', models.CharField(help_text='UI copy, e.g. Approve.', max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('next_state', models.CharField(max_length=64)),
                ('required_permissions', models.JSONField(default=list, help_text='Every capability the actor must hold.')),
                ('allow_self_approval', models.BooleanField(default=False)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='workflow.workflow')),
            ],
            options={
                'db_table': 'workflow_workflowtransition',
                'unique_together': {('workflow', 'state', 'action')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=64)),
                ('operator', models.CharField(help_text='One of eq, ne, gt, gte, lt, lte, in, not_in.', max_length=8)),
                ('value', models.JSONField(help_text='Compared value; list for in/not_in.')),
                ('transition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='workflow.workflowtransition')),
            ],
            options={
                'db_table': 'workflow_workflowcondition',
            },
        ),
        migrations.CreateModel(
            name='WorkflowAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(max_length=120)),
                ('voucher_id', models.CharField(max_length=64)),
                ('state', models.CharField(help_text='State entered by the recorded action.', max_length=64)),
                ('action', models.CharField(max_length=64)),
                ('status', models.CharField(default='Open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_workflowaction',
                'indexes': [models.Index(fields=['voucher_type', 'voucher_id'], name='workflow_wo_voucher_6aa87f_idx'), models.Index(fields=['status'], name='workflow_wo_status_5b2852_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=64)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='workflow.workflow')),
            ],
            options={
                'db_table': 'workflow_workflowstate',
                'unique_together': {('workflow', 'state')},
            },
        ),
    ]
