# Generated by Django 5.2.8 on 2026-08-21 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_emergencycontact_employeecontact_employmentdetails'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('branch_code', models.CharField(blank=True, max_length=50, null=True)),
                ('account_number', models.CharField(max_length=50)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('is_primary', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='hr.employees')),
            ],
            options={
                'db_table': 'payroll_employeebankaccount',
            },
        ),
        migrations.CreateModel(
            name='PayrollProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('zig_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pay_frequency', models.CharField(default='monthly', max_length=20)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_profile', to='hr.employees')),
            ],
            options={
                'db_table': 'payroll_payrollprofile',
            },
        ),
        migrations.CreateModel(
            name='StatutoryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nssa_number', models.CharField(blank=True, max_length=50, null=True)),
                ('zimra_tax_number', models.CharField(blank=True, max_length=50, null=True)),
                ('paye_number', models.CharField(blank=True, max_length=50, null=True)),
                ('pays_aids_levy', models.BooleanField(default=True)),
                ('pension_fund', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statutory_profile', to='hr.employees')),
            ],
            options={
                'db_table': 'payroll_statutoryprofile',
            },
        ),
    ]
