# Generated by Django 5.2.8 on 2026-08-31 16:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_employeebankaccount_payrollprofile_statutoryprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Processing', 'Processing'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.UUIDField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_employees', models.IntegerField(default=0)),
                ('total_gross_usd', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_gross_zig', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_net_usd', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_net_zig', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_paye_usd', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_paye_zig', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_nssa_usd', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_nssa_zig', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'db_table': 'payroll_payrollbatch',
                'ordering': ['-period'],
            },
        ),
    ]
